- name: Checking to see if patches need to be applied.
  ansible.builtin.stat:
    path: "{{ hpl_root }}/tmp/ATLAS_PATCHING_COMPLETE"
  register: no_patches_needed

# Fixes fgrep warning being added to output and causing
# the ATLAS configuration to fail to identify aspects of 
# the given node
- name: Patching ATLAS source code (Part 1).
  ansible.builtin.replace:
    path: "{{ hpl_root }}tmp/ATLAS/CONFIG/include/atlas_sys.h"
    regexp: '2>&1'
    replace: '2>/dev/null'
  when: no_patches_needed.stat.exists == false

# Fixes 'free(): invalid pointer' error during
# ATLAS configuration
- name: Patching ATLAS source code (Part 2).
  ansible.builtin.lineinfile:
    path: "{{ hpl_root }}tmp/ATLAS/CONFIG/src/probe_comp.c"
    insertbefore: 'free\(cmnd\)'
    line: '   printf("\n");'
    firstmatch: true
  when: no_patches_needed.stat.exists == false

# Fixes 'corrupted size vs. prev_size' error during 
# ATLAS configuration
- name: Patching ATLAS source code (Part 3).
  ansible.builtin.lineinfile:
    path: "{{ hpl_root }}tmp/ATLAS/CONFIG/include/atlas_sys.h"
    insertbefore: 'if \(fgets\(sout, len, fpin\)\)'
    line: '   printf("\n");'
    firstmatch: true
  when: no_patches_needed.stat.exists == false

- name: Create 'ATLAS_PATCHING_COMPLETE' file.
  ansible.builtin.file:
    path: "{{ hpl_root }}/tmp/ATLAS_PATCHING_COMPLETE"
    state: touch
    mode: 0644